### PR TITLE
🚀 Added support for Android SDK 31 & more

### PR DESCRIPTION
**Pull request by germainkevinbusiness**
### Summary
🚀 Added support for Android SDK 31
😄 Updated dependencies to the latest stable versions & left the kotlin-gradle-plugin to version 1.5.31, because the latest 1.6.10 causes bugs & is not yet fully supported by certain dependencies in thi project
👌 Tested the whole project in portrait & landscape mode on an Android Studio Emulator & it works just fine

### CODE REVIEW

**Comment by hadiyarajesh** [comment]
@germainkevinbusiness could you please use stable version (instead of alpha version) of room library (and any other library, if required)?

**Comment by germainkevinbusiness** [comment]
Sure

**Comment by germainkevinbusiness** [comment]
I did 

> @germainkevinbusiness could you please use stable version (instead of alpha version) of room library (and any other library, if required)?

I just updated the libraries and tested the project on an Android Studio Emulator 👍🏾

**Review by hadiyarajesh — APPROVED** [review]
Thanks @kevingermainbusiness

**Pull request merged**
