### PR TITLE
Improved Resource status information

### PR DESCRIPTION
**Pull request by DATL4G**
## This simplifies error handling and provides needed information

- changed Resource Status to sealed class
- only pass error message in error status
- error message is no longer nullable and always present
- added statusCode to error status

### CODE REVIEW

**Comment by hadiyarajesh** [comment]
This is indeed very useful. Thanks for valuable commit.

**Comment by DATL4G** [comment]
@hadiyarajesh nice to see it hot merged!

Is it possible to create a release anytime soon? As I wanna rely on this change.

Additionally check your maven repository, the latest release (2.0.2) can't be used because of wrong/non-existent package name. Maybe something went wrong during the build process and you just have to trigger it again.

**Comment by hadiyarajesh** [comment]
@DATL4G Yes, I'm aware of this build problem as mentioned in this [Issue](https://github.com/hadiyarajesh/flower/issues/12). I tried publishing multiple times but saw Gradle warning of no automatic metadata publishing using [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin). I guess this is what causing the issue.

I'm bit acquired now and having trouble to focus on it, but I'll work on it as soon as possible. Meanwhile, you can give it a try if you're interested.

**Comment by hadiyarajesh** [comment]
@DATL4G thanks for going ahead and publishing it. I managed to publish using Gradle Nexus Publish Plugin and new version [2.0.3](https://github.com/hadiyarajesh/flower/releases/tag/2.0.3) is now available on maven central. I also found the issue in previous releases. I mistakenly used `isMinifyEnabled = true` in library build file for release build and that was causing the non-existent package error. I've corrected it [here](https://github.com/hadiyarajesh/flower/blob/8caede738c1e0873104bf2d07197defbbf2130f6/Flower/build.gradle.kts#L23).

**Comment by DATL4G** [comment]
Example: https://github.com/hadiyarajesh/flower/blob/master/app/src/main/java/com/hadiyarajesh/flowersample/extensions/ActivityMainExt.kt#L74-L94

**Comment by DATL4G** [comment]
I think it's okay but if you don't like, consider to change the other types to classes as well.
I wouldn't revert the change, instead you could pass the data in loading and success only.
Error should never pass data

**Comment by hadiyarajesh** [comment]
I tried to use data class for sucess and error status, but faced generic issue. If you want to have a look, here's the [SO question](https://stackoverflow.com/questions/72941987/kotlin-generic-type-issue-with-reified?noredirect=1#comment128847806_72941987)

Also, I'm planning to re-archtecture library. As you're valuable contributor,  let me know if you're interested to work on it.

**Comment by DATL4G** [comment]
I would like to restructure the library as well, because I want to make it compatible with another library.

I think it's the best to start a discussion or a project (with permissions?) to get started and plan the new architecture.

**Comment by hadiyarajesh** [comment]
yes, i thought the same, but wnated to inform you before starting a discussion. Here's the [discussion](https://github.com/hadiyarajesh/flower/discussions/14)

**Pull request merged**
